use_frameworks!

target 'YDDeviceTool_Example' do
  pod 'YDDeviceTool', :path => '../'

  target 'YDDeviceTool_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end

